### ISSUE TITLE
špatné přesměrování na www

### ISSUE THREAD

**Issue by nesnera** [otevrenamesta/otevrenamesta.github.io#15]
pokud nezadám www. tak mi to ten web nenalezne takže je špatně nastavený htaccess

**Comment by stepanfichtner** [comment]
mělo by pomoc do htaccessu v kořenovém adresáři přidat následující

RewriteEngine On
RewriteBase /
RewriteCond %{HTTP_HOST} !^otevrenamesta.cz$ [NC]
RewriteRule ^(.*)$ https://otevrenamesta.cz/$1 [L,R=301]

**Comment by nesnera** [comment]
opraveno
